### ISSUE TITLE
Can MMPose run in Window 10?

### ISSUE THREAD

**Issue by MIMOS-Chien** [jin-s13/xtcocoapi#12]
Hi, it seems that I managed to install MMPose in Window 10. But, when I try to run on the cmd below:

```bash
C:\MMPOSE>python demo/bottom_up_video_demo.py \configs/bottom_up/hrnet/coco/hrnet_w32_coco_512x512.py \path/hrnet_w32_coco_512x512-bcb8c247_20200816.pth \--video-path demo/demo_video.mp4 \--out-video-root vis_results 
```
It comes out an error message: usage: bottom_up_video_demo.py [-h] [--video-path VIDEO_PATH] [--show] [--out-video-root OUT_VIDEO_ROOT]
                               [--device DEVICE] [--kpt-thr KPT_THR]
                               pose_config pose_checkpoint
bottom_up_video_demo.py: error: unrecognized arguments: \--video-path demo/demo_video.mp4 \--out-video-root vis_results

Kindly advise. TQVM

**Comment by innerlee** [comment]
Delete the `\` in the command and try again. It is used to join lines in unix.

**Comment by MIMOS-Chien** [comment]
Not work too.


(c:\mmpose\envs) C:\MMPOSE>python demo/bottom_up_video_demo.py configs/bottom_up/hrnet/coco/hrnet_w32_coco_512x512.py path/hrnet_w32_coco_512x512-bcb8c247_20200816.pth --video-path demo/demo_video.mp4 --out-video-root vis_results
Use load_from_local loader
Traceback (most recent call last):
  File "demo/bottom_up_video_demo.py", line 102, in <module>
    main()
  File "demo/bottom_up_video_demo.py", line 92, in main
    if cv2.waitKey(1) & 0xFF == ord('q'):
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1drr4hl0\opencv\modules\highgui\src\window.cpp:717: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

**Comment by innerlee** [comment]
We can add some tips in the installation/readme
