### ISSUE TITLE
change maxDets for keypoints evaluation

### ISSUE THREAD

**Issue by zwfcrazy** [jin-s13/xtcocoapi#15]
Hi, I want to change maxDets for keypoints evaluation, please add this instead of using a fixed maxDet = 20.

**Comment by jin-s13** [comment]
Can you explain your use case in more details? I am not sure if this use case is general enough. 
Do you want to evaluate keypoint estimation on a private dataset or on a public dataset?

**Comment by jin-s13** [comment]
And why do you want to change this?

**Comment by zwfcrazy** [comment]
In my case, I only require the network to recognize one person in a photo, the person may be the dominant one or the one closest to the center of a photo. I'm not sure if this is a general case...

**Comment by jin-s13** [comment]
Instead of changing the evaluation codes, I recommend adding a post-processing procedure to only keep one dominant person before evaluation.
