### ISSUE TITLE
AP(M) calculation seems incorrect with xtcocotools 1.10

### ISSUE THREAD

**Issue by ly015** [jin-s13/xtcocoapi#25]
As reported in an issue of MMPose (https://github.com/open-mmlab/mmpose/issues/1280), AP(M) calculation gets different results with xtcocotools 1.10 and 1.08, and the former is much lower. It seems an xtcocotools issue, so could you please help check the reason. Thank you very much.

**Comment by jin-s13** [comment]
Yes, it is indeed a bug. And this bug is fixed in v1.12, see #24
