### ISSUE TITLE
Install fails on linux

### ISSUE THREAD

**Issue by txnf** [jin-s13/xtcocoapi#38]
After I ran pip install -r requirements.txt

I ran the install and it fails, I also tried building from source..  not sure how to proceed

$ python setup.py install

running install
/home//anaconda3/envs/autobonk/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home//anaconda3/envs/autobonk/lib/python3.11/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing manifest file 'xtcocotools.egg-info/SOURCES.txt'
running install_lib
running build_py
running build_ext
gcc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/jmb/anaconda3/envs/autobonk/include -fPIC -O2 -isystem /home//anaconda3/envs/autobonk/include -fPIC -I/home//anaconda3/envs/autobonk/lib/python3.11/site-packages/numpy/core/include -I./common -I/home//anaconda3/envs/autobonk/include/python3.11 -c ../common/maskApi.c -o build/temp.linux-x86_64-3.11/../common/maskApi.o
gcc: error: ../common/maskApi.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by jin-s13** [comment]
solved by #37
