### ISSUE TITLE
Workflow failed to build and publish for linux

### ISSUE THREAD

**Issue by nzikos** [jin-s13/xtcocoapi#40]
There are no linux versions on pypi repo for v1.14
The workfow failed to build and publish the packages.

**Comment by ilya-sha** [comment]
@jin-s13 Can you publish linux versions pypi for v1.14?

**Comment by jin-s13** [comment]
oh. the workflow failed. I will check.

**Comment by jin-s13** [comment]
solved in v1.14.3
